src/basingse/utils/urls.py
from urllib.parse import urlencode

from flask import Request
from flask import url_for


def rewrite_url(request: Request, **kwargs: str) -> str:
    args = dict(**request.args)
    args.update(kwargs)
    return f"{request.base_url}?{urlencode(args)}"


def rewrite_endpoint(request: Request, **kwargs: str) -> str:
    assert request.endpoint is not None, "Request has no endpoint."
    return rewrite_update(request, request.endpoint, **kwargs)


def rewrite_update(request: Request, endpoint: str, **kwargs: str) -> str:
    if request.view_args:
        args = dict(**request.view_args)
    else:
        args = dict()
    args.update(request.args)
    args.update(kwargs)
    return url_for(endpoint, **args)

src/basingse/customize/views.py
from typing import Never

import structlog
from flask import abort
from flask import Blueprint
from flask import flash
from flask import render_template
from flask.typing import ResponseReturnValue as IntoResponse
from flask_login import current_user
from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import LogoSize
from .models import SiteSettings
from basingse import svcs
from basingse.page.models import Page

bp = Blueprint("customize", __name__, template_folder="templates")

logger = structlog.get_logger()


def logo_endpoint(size: LogoSize) -> IntoResponse:
    """Generic implementation for a logo endpoint."""
    settings = svcs.get(SiteSettings)
    logo = settings.logo.size(size)
    if logo is None:
        logger.warning("No logo found for size", size=size, debug=True)
        abort(404)

    session = svcs.get(Session)
    logo = session.merge(logo, load=False)
    return logo.send()


@bp.route("/brand/logo/<size>")
def logo(size: str) -> IntoResponse:
    try:
        sz = LogoSize[size.upper()]
    except KeyError:
        abort(400, f"Invalid logo size: {size}")
    else:
        return logo_endpoint(sz)


@bp.route("/favicon.ico")
def favicon() -> IntoResponse:
    return logo_endpoint(LogoSize.FAVICON)


@bp.route("/apple-touch-icon.png")
def apple_touch_icon() -> IntoResponse:
    return logo_endpoint(LogoSize.LARGE)


@bp.route("/apple-touch-icon-precomposed.png")
def apple_touch_icon_precomposed() -> IntoResponse:
    return logo_endpoint(LogoSize.LARGE)


def no_homepage(settings: SiteSettings) -> Never:
    if current_user.is_authenticated:
        flash("No homepage found, please set one in the admin interface", "warning")
    logger.warning("No homepage found, please set one in the admin interface", settings=settings)
    abort(404)


@bp.route("/")
def home() -> IntoResponse:
    settings = svcs.get(SiteSettings)
    session = svcs.get(Session)

    if settings.homepage_id is None:
        no_homepage(settings)

    # coverage is not needed here because the homepage_id is a foreign key, so this should
    # never happen
    if (homepage := session.get(Page, settings.homepage_id)) is None:  # pragma: nocover
        # Check if the homepage is unpublished
        if (
            session.scalar(
                select(Page).where(Page.id == settings.homepage_id).execution_options(include_upublished=True)
            )
            is not None
        ):
            logger.warning(
                "Homepage is set, but the ID points to an unpublished page",
                homepage_id=settings.homepage_id,
            )
            abort(404)

        logger.warning(
            "Homepage is set, but the ID points to a missing page",
            homepage_id=settings.homepage_id,
        )
        abort(404)

    return render_template(["home.html", "page.html"], page=homepage)

src/basingse/templates/_colormode.html
<button class="text-reset btn btn-link nav-link dropdown-toggle" id="color-theme-switcher" data-bs-toggle="dropdown"
    aria-expanded="false" aria-label="Toggle theme (light)">
    <span id="color-theme-icon">{{ icon('sun-fill') }}</span>
    <span class="d-lg-none" id="colot-theme-text">Toggle theme</span>
</button>
<ul class="dropdown-menu" id="color-theme-menu" aria-labelledby="color-theme-text">
    <li>
        <button type="button" class="dropdown-item" id="lighttheme" data-bs-theme-value="light" aria-pressed="false">
            {{ icon('sun-fill') }}Light
        </button>
    </li>
    <li>
        <button type="button" class="dropdown-item" id="darktheme" data-bs-theme-value="dark" aria-pressed="false">
            {{ icon('moon-stars-fill') }}Dark
        </button>
    </li>
</ul>

src/basingse/templates/_devbar.html
{% from "_env.html" import env_pill %}

<div class="m-1 rounded py-1 px-3 bss-devbar" id="devbar">
    <!-- DevBar -->
    <ul class="navbar-nav d-flex flex-row">
        <li class="nav-item pe-2 d-inline-flex align-items-center">
            {{ env_pill() }}
        </li>
        <li class="nav-item pe-2 d-inline-flex align-items-center">
            <a href="/" class="text-reset nav-link d-inline-flex align-items-center">{{ icon('house-fill') }}</a>
        </li>
        <li class="nav-item pe-2 d-inline-flex align-items-center">
            <a href="{{ url_for('admin.home') }}" class="text-reset nav-link d-inline-flex align-items-center">{{
                icon('gear') }}</a>
        </li>
        <li class="nav-item pe-2 d-inline-flex align-items-center">
            {% include "_lock.html" %}
        </li>
        <li class="nav-item dropdown">
            {% include "_colormode.html" %}
        </li>
    </ul>
    <!-- DevBar -->
</div>

src/basingse/templates/_env.html
{% from "_icon.html" import icon %}
{% macro env_pill() %}
{% if config['ENV'].lower() == 'development' %}
{% set color = 'secondary' %}
{% elif config['ENV'].lower() == 'preview' %}
{% set color = 'primary' %}
{% else %}
{% set color = 'danger' %}
{% endif %}
<span class="badge rounded-pill text-bg-{{color}}">{{ config['ENV'] | upper }}</span>
{% endmacro %}

src/basingse/templates/_flash.html
{% macro message_category_class(category) %}
{% if category == 'error' %}
alert-danger
{% elif category == 'warning' %}
alert-warning
{% elif category == 'success' %}
alert-info
{% endif %}
{% endmacro %}

{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
<div class="row my-3">
    <div class="col-5">

        {% for (category, message) in messages %}
        <div class="alert {{ message_category_class(category) }}">
            <h6 class="alert-heading d-inline-flex align-items-center">{{ icon('exclamation-triangle')
                }} <span class="ps-1">{{ category }}:</span></h6>
            <p>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endwith %}

src/basingse/templates/_footer.html
<div class="row mt-5 py-3 px-5" data-bs-theme="dark">
    <div class="col-md-4">
        <div class="d-flex align-items-baseline">
            <div class="mx-3 text-secondary">
                {% include "_lock.html" %}
            </div>
            {% if site_settings is defined %}
            <div>&copy; 2023 {{ site_settings.title }}</div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-4">
    </div>
    {% if site_settings is defined %}
    <div class="col-md-4 text-secondary text-end">
        {{ site_settings.footer_message | markdown }}
    </div>
    {% endif %}
</div>

src/basingse/templates/_icon.html
{% macro icon(name, width=16, height=16, classes="bi-inline") %}
<svg class="bi pe-none {{ classes }}" fill="currentColor">
    <use xlink:href="{{ url_for('bootlace.static', filename='icons/bootstrap-icons.svg') }}#{{ name }}" />
</svg>
{% endmacro %}

{{ icon(icon.name, width=icon.width, height=icon.height) }}

src/basingse/templates/_lock.html
{% if current_user.is_authenticated %}
<a class="text-reset d-inline-flex align-items-center nav-link" href="{{ url_for('admin.home') }}">
    {{ icon("unlock-fill")}}
</a>
{% else %}
<a class="text-reset d-inline-flex align-items-center nav-link"
    href="{{ url_for_next('auth.login', next=url_for('admin.home')) }}">
    {{ icon("lock-fill") }}
</a>
{% endif %}

src/basingse/templates/_topbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-dark" id="topbar">
    <!-- TopBar -->
    <div class="container-fluid">
        {% if config['ENV'].lower() != 'production' %}
        {% include "_devbar.html" %}
        {% endif %}
        <div class="navbar-collapse collapse">
            <ul class="navbar-nav ms-4 me-auto mb-2 mb-lg-0 text-uppercase">
                <li class="nav-item pe-2">
                    <a class="nav-link" href="{{ site_settings.contactpage.url }}">{{
                        site_settings.contact_message }}</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="d-inline-flex justify-content-end">
        <ul class="navbar-nav flex-row ms-4 me-auto mb-0 pe-2">
            {% for link in social_links %}
            <li class="nav-item pe-2 text-lg-center">
                <a class="nav-link d-flex" href="{{ link.url }}">
                    {% if link.image %}
                    <div class="pe-2 d-inline-flex align-items-center opacity-50"><img
                            src=" {{ url_for('attachment.id', id=link.image.id ) }}" width="16" , height="16">
                    </div>
                    {% else %}
                    <div class="pe-2 d-inline-flex align-items-center">{{ icon(link.icon) }}</div>
                    {% endif %}
                    <div class="d-none d-md-inline-flex">{{ link.name }}</div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <!-- TopBar -->
</nav>

src/basingse/templates/base.html
{% extends "core.html" %}


{% block body %}
<header>
    {% block navbar %}
    {% if navbar %}{{ render(navbar) }}{% endif %}
    {% endblock %}
</header>
<main class="container-lg flex-grow-1 mb-5">
    {% block flash %}
    {% include "_flash.html" %}
    {% endblock flash %}
    {% block main %}{% endblock %}
</main>
{% endblock %}

{% block footer %}
<div class="container-fluid mt-auto">
    {% include "_footer.html" %}
</div>
{% endblock %}

src/basingse/templates/core.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>

    {% if site_settings is defined and site_settings.logo.favicon_id %}
    <link rel="icon" href="{{ url_for('customize.favicon') }}">
    {% else %}
    <link rel="icon" href="{{ url_for('basingse.static', filename='img/logo/icon32.png') }}">
    {% endif %}

    {% block style %}
    {{ assets.resources('basingse.bootstrap', '.css') | safe }}
    {{ assets.resources('basingse.main', '.css') | safe }}
    {% if config.get('DEBUG') %}
    {{ assets.resources('basingse.debug', '.css') | safe }}
    {% endif %}
    {% endblock %}
</head>

{% from "_icon.html" import icon %}

<body class="d-flex flex-column min-vh-100">
    {% block body %}
    {% endblock %}
    <footer>
        {% block footer %}
        {% endblock %}
        {% block scripts %}
        {{- assets.resources('basingse.bootstrap', '.js') | safe -}}
        {{- assets.resources('basingse.main', '.js') | safe -}}
        {%- if config.get('DEBUG') -%}
        <!-- {{- assets.resources('basingse.debug', '.js') | safe -}} -->
        {%- endif -%}
        {% endblock %}
    </footer>
</body>

</html>

src/basingse/templates/land.html
{% extends "base.html" %}

{% block title %}
{{ land.title }} | {{ site_settings.title }}
{% endblock %}

{% block main %}
<article class="container pt-4 clearfix">
    <div class="row my-4">
        <div class="col-md-8">
            {{ land.contents | markdown }}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</article>
{% endblock %}

src/basingse/templates/not_found.html
{% extends "base.html" %}

{% block title %}
Not Found | {{ site_settings.title }}
{% endblock %}

{% block main %}
<article class="container pt-4 clearfix">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item "><a class="text-reset" href="{{ url_for('home') }}">Home</a>
            </li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-8">
            <h2>Oops! There is nothing here!</h2>
            <p>This page cannot be found.</p>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</article>
{% endblock %}

src/basingse/templates/server_error.html
{% extends "base.html" %}

{% block title %}
Server Error | {{ site_settings.title }}
{% endblock %}

{% block main %}
<article class="container pt-4 clearfix">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item "><a class="text-reset" href="{{ url_for('home') }}">Home</a>
            </li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-8">
            <h2>Oops! Something went wrong!</h2>
            <p>We're sorry, something has gone wrong. This has been reported to the maintaniers. You might want to go
                home, or refresh to try again.</p>

        </div>
        <div class="col-md-4">
        </div>
    </div>
</article>
{% endblock %}